
# Use: curl --user admin:password -X POST localhost:9092/shutdown
management.port: 9092
endpoints.shutdown.enabled: true
security.user.name: admin
security.user.password: password

dvesta-gateway.username: s1
dvesta-gateway.password: pass-s1

---
spring.profiles: local
dvesta-gateway.websock-endpoint: ws://localhost:8093/gateway-websock

---
spring.profiles: prod
dvesta-gateway.websock-endpoint: ws://caglabs.se/dvesta-gateway/gateway-websock
